name: china-robotics-news

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"   # 매일 08:00 UTC = 17:00 KST(Asia/Seoul)

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Fetch & Render (last 24h)
        env:
          LOCAL_TZ: Asia/Seoul     # 중국 기준이면 Asia/Shanghai 로 변경
          WINDOW_HOURS: "24"
          SKIP_HTML: "0"
          EXTRACT_BODY: "1"
        run: python src/fetch.py
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
