name: china-robotics-news
on:
  schedule:
    - cron: "17 */4 * * *"   # every 4 hours (UTC)
  workflow_dispatch: {}
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Fetch & Render
        run: python src/fetch.py
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
