name: pages-smoke
on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/pages-smoke.yml"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create minimal docs
        run: |
          mkdir -p docs
          cat > docs/index.html << 'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Pages OK</title>
          <h1>GitHub Pages Smoke Test ✅</h1>
          <p>이 화면이 보이면 Pages는 정상입니다.</p>
          HTML
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
